// Old-HSK 2.0 readings are sourced from
// https://github.com/clem109/hsk-vocabulary.
// Only ambiguous words requiring a non-first upstream form are listed here.
const preferredHsk2Pinyin = <String, String>{
  '东西': 'dōng xi',
  '都': 'dōu',
  '读': 'dú',
  '多少': 'duō shao',
  '个': 'gè',
  '几': 'jǐ',
  '看': 'kàn',
  '冷': 'lěng',
  '吗': 'ma',
  '那': 'nà',
  '能': 'néng',
  '年': 'nián',
  '钱': 'qián',
  '日': 'rì',
  '三': 'sān',
  '上': 'shàng',
  '书': 'shū',
  '水': 'shuǐ',
  '听': 'tīng',
  '喂': 'wèi',
  '坐': 'zuò',
  '吧': 'ba',
  '白': 'bái',
  '百': 'bǎi',
  '比': 'bǐ',
  '别': 'bié',
  '错': 'cuò',
  '得': 'de',
  '高': 'gāo',
  '告诉': 'gào su',
  '还': 'hái',
  '号': 'hào',
  '黑': 'hēi',
  '红': 'hóng',
  '累': 'lèi',
  '离': 'lí',
  '路': 'lù',
  '门': 'mén',
  '便宜': 'pián yi',
  '妻子': 'qī zi',
  '题': 'tí',
  '为': 'wèi',
  '向': 'xiàng',
  '新': 'xīn',
  '雪': 'xuě',
  '要': 'yào',
  '也': 'yě',
  '阴': 'yīn',
  '鱼': 'yú',
  '元': 'yuán',
  '张': 'zhāng',
  '着': 'zhe',
  '只': 'zhǐ',
  '啊': 'a',
  '班': 'bān',
  '包': 'bāo',
  '差': 'chà',
  '地方': 'dì fang',
  '东': 'dōng',
  '段': 'duàn',
  '更': 'gèng',
  '故事': 'gù shi',
  '关': 'guān',
  '过去': 'guò qu',
  '花': 'huā',
  '黄': 'huáng',
  '教': 'jiāo',
  '角': 'jiǎo',
  '蓝': 'lán',
  '楼': 'lóu',
  '马': 'mǎ',
  '米': 'mǐ',
  '南': 'nán',
  '鸟': 'niǎo',
  '胖': 'pàng',
  '骑': 'qí',
  '秋': 'qiū',
  '双': 'shuāng',
  '万': 'wàn',
  '西': 'xī',
  '夏': 'xià',
  '越': 'yuè',
  '祝': 'zhù',
  '场': 'chǎng',
  '成功': 'chéng gōng',
  '戴': 'dài',
  '大夫': 'dài fu',
  '刀': 'dāo',
  '底': 'dǐ',
  '富': 'fù',
  '干': 'gàn',
  '过': 'guò',
  '汗': 'hàn',
  '好处': 'hǎo chu',
  '火': 'huǒ',
  '假': 'jiǎ',
  '结果': 'jié guǒ',
  '宽': 'kuān',
  '连': 'lián',
  '满': 'mǎn',
  '弄': 'nòng',
  '起来': 'qi lai',
  '狮子': 'shī zi',
  '帅': 'shuài',
  '孙子': 'sūn zi',
  '台': 'tái',
  '谈': 'tán',
  '弹': 'tán',
  '汤': 'tāng',
  '趟': 'tàng',
  '咸': 'xián',
  '现代': 'xiàn dài',
  '行': 'xíng',
  '修': 'xiū',
  '页': 'yè',
  '友好': 'yǒu hǎo',
  '与': 'yǔ',
  '脏': 'zāng',
  '重点': 'zhòng diǎn',
  '薄': 'báo',
  '背': 'bèi',
  '朝': 'cháo',
  '乘': 'chéng',
  '丑': 'chǒu',
  '大方': 'dà fang',
  '倒': 'dào',
  '地道': 'dì dao',
  '丁': 'dīng',
  '方': 'fāng',
  '非': 'fēi',
  '盖': 'gài',
  '官': 'guān',
  '管子': 'guǎn zi',
  '哈': 'hā',
  '和平': 'hé píng',
  '结实': 'jiē shi',
  '节': 'jié',
  '克': 'kè',
  '雷': 'léi',
  '龙': 'lóng',
  '露': 'lù',
  '毛': 'máo',
  '匹': 'pǐ',
  '片': 'piàn',
  '平': 'píng',
  '浅': 'qiǎn',
  '枪': 'qiāng',
  '抢': 'qiǎng',
  '青': 'qīng',
  '圈': 'quān',
  '诗': 'shī',
  '时代': 'shí dài',
  '提': 'tí',
  '吐': 'tù',
  '闻': 'wén',
  '吓': 'xià',
  '项': 'xiàng',
  '延长': 'yán cháng',
  '摇': 'yáo',
  '正': 'zhèng',
  '支': 'zhī',
  '直': 'zhí',
  '钟': 'zhōng',
  '重': 'zhòng',
  '资源': 'zī yuán',
  '挨': 'ái',
  '安宁': 'ān níng',
  '熬': 'áo',
  '奔驰': 'bēn chí',
  '本事': 'běn shi',
  '扁': 'biǎn',
  '盛': 'chéng',
  '秤': 'chèng',
  '出息': 'chū xi',
  '刺': 'cì',
  '大意': 'dà yi',
  '淡水': 'dàn shuǐ',
  '党': 'dǎng',
  '恶心': 'ě xīn',
  '番': 'fān',
  '方言': 'fāng yán',
  '分量': 'fèn liang',
  '丰满': 'fēng mǎn',
  '富裕': 'fù yù',
  '复兴': 'fù xīng',
  '高明': 'gāo míng',
  '公道': 'gōng dao',
  '工夫': 'gōng fu',
  '呵': 'hē',
  '将军': 'jiāng jūn',
  '井': 'jǐng',
  '扛': 'káng',
  '孔': 'kǒng',
  '啦': 'la',
  '联想': 'lián xiǎng',
  '搂': 'lǒu',
  '嘛': 'ma',
  '枚': 'méi',
  '眯': 'mī',
  '嗯': 'en',
  '哦': 'ò',
  '颇': 'pō',
  '铺': 'pū',
  '翘': 'qiào',
  '人家': 'rén jia',
  '拾': 'shí',
  '束': 'shù',
  '耍': 'shuǎ',
  '哇': 'wa',
  '网络': 'wǎng luò',
  '威信': 'wēi xìn',
  '兴隆': 'xīng lóng',
  '翼': 'yì',
  '熨': 'yùn',
  '攒': 'zǎn',
  '折': 'zhé',
  '振兴': 'zhèn xīng',
  '粥': 'zhōu',
  '拽': 'zhuài',
  '幢': 'zhuàng',
  '组': 'zǔ',
};

// These homographs share the same pinyin, so pronunciation alone cannot
// distinguish the learner-facing HSK form.
const preferredHsk2Traditional = <String, String>{'台': '臺', '钟': '鐘'};
