// Old-HSK 2.0 readings are sourced from
// https://github.com/clem109/hsk-vocabulary.
// Only ambiguous words requiring a non-first upstream form are listed here.
const preferredHsk2Pinyin = <String, String>{
  '俩': 'liǎ',
  '得罪': 'dé zui',
  '蒙': 'méng',
  '东西': 'dōng xi',
  '都': 'dōu',
  '读': 'dú',
  '多少': 'duō shao',
  '个': 'gè',
  '几': 'jǐ',
  '看': 'kàn',
  '冷': 'lěng',
  '吗': 'ma',
  '那': 'nà',
  '能': 'néng',
  '年': 'nián',
  '钱': 'qián',
  '日': 'rì',
  '三': 'sān',
  '上': 'shàng',
  '书': 'shū',
  '水': 'shuǐ',
  '听': 'tīng',
  '喂': 'wèi',
  '坐': 'zuò',
  '吧': 'ba',
  '白': 'bái',
  '百': 'bǎi',
  '比': 'bǐ',
  '别': 'bié',
  '错': 'cuò',
  '得': 'de',
  '高': 'gāo',
  '告诉': 'gào su',
  '还': 'hái',
  '号': 'hào',
  '黑': 'hēi',
  '红': 'hóng',
  '累': 'lèi',
  '离': 'lí',
  '路': 'lù',
  '门': 'mén',
  '便宜': 'pián yi',
  '妻子': 'qī zi',
  '题': 'tí',
  '为': 'wèi',
  '向': 'xiàng',
  '新': 'xīn',
  '雪': 'xuě',
  '要': 'yào',
  '也': 'yě',
  '阴': 'yīn',
  '鱼': 'yú',
  '元': 'yuán',
  '张': 'zhāng',
  '着': 'zhe',
  '只': 'zhǐ',
  '啊': 'a',
  '班': 'bān',
  '包': 'bāo',
  '差': 'chà',
  '地方': 'dì fang',
  '东': 'dōng',
  '段': 'duàn',
  '更': 'gèng',
  '故事': 'gù shi',
  '关': 'guān',
  '过去': 'guò qu',
  '花': 'huā',
  '黄': 'huáng',
  '教': 'jiāo',
  '角': 'jiǎo',
  '蓝': 'lán',
  '楼': 'lóu',
  '马': 'mǎ',
  '米': 'mǐ',
  '南': 'nán',
  '鸟': 'niǎo',
  '胖': 'pàng',
  '骑': 'qí',
  '秋': 'qiū',
  '双': 'shuāng',
  '万': 'wàn',
  '西': 'xī',
  '夏': 'xià',
  '越': 'yuè',
  '祝': 'zhù',
  '场': 'chǎng',
  '成功': 'chéng gōng',
  '戴': 'dài',
  '大夫': 'dài fu',
  '刀': 'dāo',
  '底': 'dǐ',
  '富': 'fù',
  '干': 'gàn',
  '过': 'guò',
  '汗': 'hàn',
  '好处': 'hǎo chu',
  '火': 'huǒ',
  '假': 'jiǎ',
  '结果': 'jié guǒ',
  '宽': 'kuān',
  '连': 'lián',
  '满': 'mǎn',
  '弄': 'nòng',
  '起来': 'qi lai',
  '狮子': 'shī zi',
  '帅': 'shuài',
  '孙子': 'sūn zi',
  '台': 'tái',
  '谈': 'tán',
  '弹': 'tán',
  '汤': 'tāng',
  '趟': 'tàng',
  '咸': 'xián',
  '现代': 'xiàn dài',
  '行': 'xíng',
  '修': 'xiū',
  '页': 'yè',
  '友好': 'yǒu hǎo',
  '与': 'yǔ',
  '脏': 'zāng',
  '重点': 'zhòng diǎn',
  '薄': 'báo',
  '背': 'bèi',
  '朝': 'cháo',
  '乘': 'chéng',
  '丑': 'chǒu',
  '大方': 'dà fang',
  '倒': 'dào',
  '地道': 'dì dao',
  '丁': 'dīng',
  '方': 'fāng',
  '非': 'fēi',
  '盖': 'gài',
  '官': 'guān',
  '管子': 'guǎn zi',
  '哈': 'hā',
  '和平': 'hé píng',
  '结实': 'jiē shi',
  '节': 'jié',
  '克': 'kè',
  '雷': 'léi',
  '龙': 'lóng',
  '露': 'lù',
  '毛': 'máo',
  '匹': 'pǐ',
  '片': 'piàn',
  '平': 'píng',
  '浅': 'qiǎn',
  '枪': 'qiāng',
  '抢': 'qiǎng',
  '青': 'qīng',
  '圈': 'quān',
  '诗': 'shī',
  '时代': 'shí dài',
  '提': 'tí',
  '吐': 'tù',
  '闻': 'wén',
  '吓': 'xià',
  '项': 'xiàng',
  '延长': 'yán cháng',
  '摇': 'yáo',
  '正': 'zhèng',
  '支': 'zhī',
  '直': 'zhí',
  '钟': 'zhōng',
  '重': 'zhòng',
  '资源': 'zī yuán',
  '挨': 'ái',
  '安宁': 'ān níng',
  '熬': 'áo',
  '奔驰': 'bēn chí',
  '本事': 'běn shi',
  '扁': 'biǎn',
  '盛': 'chéng',
  '秤': 'chèng',
  '出息': 'chū xi',
  '刺': 'cì',
  '大意': 'dà yi',
  '淡水': 'dàn shuǐ',
  '党': 'dǎng',
  '恶心': 'ě xīn',
  '番': 'fān',
  '方言': 'fāng yán',
  '分量': 'fèn liang',
  '丰满': 'fēng mǎn',
  '富裕': 'fù yù',
  '复兴': 'fù xīng',
  '高明': 'gāo míng',
  '公道': 'gōng dao',
  '工夫': 'gōng fu',
  '呵': 'hē',
  '将军': 'jiāng jūn',
  '井': 'jǐng',
  '扛': 'káng',
  '孔': 'kǒng',
  '啦': 'la',
  '联想': 'lián xiǎng',
  '搂': 'lǒu',
  '嘛': 'ma',
  '枚': 'méi',
  '眯': 'mī',
  '嗯': 'en',
  '哦': 'ò',
  '颇': 'pō',
  '铺': 'pū',
  '翘': 'qiào',
  '人家': 'rén jia',
  '拾': 'shí',
  '束': 'shù',
  '耍': 'shuǎ',
  '哇': 'wā',
  '网络': 'wǎng luò',
  '威信': 'wēi xìn',
  '兴隆': 'xīng lóng',
  '翼': 'yì',
  '熨': 'yùn',
  '攒': 'zǎn',
  '折': 'zhé',
  '振兴': 'zhèn xīng',
  '粥': 'zhōu',
  '拽': 'zhuài',
  '幢': 'zhuàng',
  '组': 'zǔ',
};

// These homographs share the same pinyin, so pronunciation alone cannot
// distinguish the learner-facing HSK form.
const preferredHsk2Traditional = <String, String>{'台': '臺', '钟': '鐘', '蒙': '蒙'};

// Reviewed study senses from docs/vocabulary-review-2026-10-10.md.
// These are editorial choices, kept separate from the pinned upstream sources.
const reviewedStudyMeanings = <String, String>{
  // Preserve established study glosses where the glossary has branch-count,
  // spelling, or sandhi inconsistencies. These explicit choices keep stricter
  // default matching from replacing useful teaching senses with the first raw sense.
  "个": "general measure word",
  "哪": "which",
  "一起": "together",
  "别": "don't do something",
  "吧": "particle indicating polite suggestion",
  "知道": "know",
  "一会儿": "a while",
  "一样": "the same",
  "一直": "always",
  "一般": "general",
  "可爱": "cute",
  "太阳": "the sun",
  "过去": "in the past",
  "一切": "all",
  "不但": "not only",
  "受不了": "cannot endure",
  "座": "classifier for mountains, bridges, tall buildings, etc.",
  "支持": "sustain",
  "起来": "beginning or continuing an action",
  "骄傲": "proud",
  "不安": "uneasy",
  "不耐烦": "impatience",
  "亲爱": "beloved",
  "佩服": "admire",
  "妨碍": "hinder",
  "恋爱": "romantic love",
  "打交道": "come into contact with",
  "残疾": "deformity",
  "热爱": "love ardently",
  "痛快": "joyful",
  "一举两得": "kill two birds with one stone",
  "一向": "all along",
  "一帆风顺": "(saying) smooth sailing",
  "一目了然": "obvious at a glance",
  "不愧": "be worthy of",
  "供不应求": "(saying) demand outstrips supply",
  "分量": "weight",
  "名额": "particular number of people",
  "嗯": "interjection expressing what?, huh? hmm? why? ok, etc.",
  "埋伏": "ambush",
  "婴儿": "baby infant",
  "左右": "about",
  "巴不得": "eagerly look forward to",
  "恶心": "disgusting",
  "意识": "realize",
  "折磨": "persecute",
  "报复": "retaliate",
  "摸索": "feel about",
  "无微不至": "in every possible way",
  "爱不释手": "love something too much to part with it",
  "草案": "draft (legislation, proposal, etc.)",
  "配偶": "mate",
  "锲而不舍": "keep on chipping away",
  "阻碍": "obstruct",
  "只": "only",
  "字典": "dictionary",
  "致力于": "to dedicate oneself to",
  "上午": "morning; before noon",
  "下": "down; below; next",
  "不": "not; no",
  "了": "particle marking a completed action or a change of state",
  "呢": "question or topic particle; what about ...?",
  "块": "piece; yuan in everyday prices",
  "字": "written character; letter",
  "家": "family; home",
  "想": "to think; to want; to miss",
  "日": "day; date; sun",
  "月": "month; moon",
  "没": "not have; did not",
  "点": "o'clock; point; a little",
  "热": "hot; heat",
  "认识": "to know a person; to recognize",
  "向": "toward; to",
  "外": "outside; outer",
  "旅游": "to travel; tourism",
  "比": "than; to compare",
  "着": "particle marking a continuing action or state",
  "离": "from; away from; to leave",
  "让": "to let; to allow; to ask someone to",
  "身体": "body; health",
  "题": "question; problem; topic",
  "位": "polite classifier for people; position",
  "作用": "effect; function; role",
  "使": "to make; to cause; to use",
  "借": "to borrow; to lend",
  "包": "bag; package; to wrap",
  "双": "pair; classifier for paired things",
  "复习": "to review study material; to revise for an exam",
  "宾馆": "hotel; guesthouse",
  "差": "poor; not good; to differ",
  "带": "to bring; to take along; belt",
  "成绩": "grades; results; achievement",
  "才": "only; only then; just",
  "把": "object-marking particle; classifier for handled objects",
  "拿": "to take; to hold",
  "条": "classifier for long or narrow things; strip",
  "楼": "building; floor; storey",
  "段": "section; stretch; paragraph",
  "班": "class; shift; team",
  "电子": "electron; electronic",
  "祝": "to wish someone well",
  "米": "metre; uncooked rice",
  "行李箱": "suitcase",
  "角": "angle; corner; one tenth of a yuan; horn",
  "还是": "or in a question; still",
  "饱": "full after eating",
  "不过": "however; but; only",
  "专业": "academic major; specialty; professional",
  "主意": "idea; suggestion",
  "估计": "to estimate; to reckon",
  "修": "to repair; to study a subject",
  "兴奋": "excited; excitement",
  "千万": "ten million; by all means; be sure to",
  "博士": "doctorate; PhD holder",
  "厉害": "formidable; impressive; severe",
  "台": "classifier for machines; platform",
  "场": "venue; classifier for events",
  "实在": "really; indeed; honest",
  "害羞": "shy; embarrassed",
  "干燥": "dry; dryness",
  "当": "to serve as; when; at",
  "指": "to point at; to refer to; finger",
  "挺": "quite; very; to straighten",
  "收入": "income; revenue",
  "无聊": "bored; boring",
  "民族": "ethnic group; nationality",
  "流行": "popular; fashionable; to circulate",
  "理发": "to get or give a haircut",
  "由": "by; from; through",
  "算": "to calculate; to count as",
  "篇": "classifier for articles or written pieces",
  "联系": "to contact; connection",
  "节约": "to save resources; economical",
  "行": "okay; to work; to be acceptable; to travel",
  "输": "to lose; to transport",
  "适应": "to adapt to",
  "遍": "classifier for a complete repetition",
  "顿": "classifier for meals; pause",
  "一旦": "once; as soon as a condition is met",
  "从事": "to engage in; to work in",
  "便": "convenient; then",
  "册": "volume; classifier for books",
  "凭": "on the basis of; to rely on",
  "则": "then; but; classifier for written items; rule",
  "功夫": "skill; effort; kung fu",
  "匹": "classifier for horses; bolt of cloth",
  "实习": "internship; practical training",
  "宣传": "publicity; to promote; propaganda",
  "届": "classifier for sessions, events or graduating classes",
  "幅": "classifier for pictures or lengths of cloth",
  "应聘": "to apply for a job",
  "开放": "to open to the public; open-minded; to bloom",
  "恐怖": "horror; terrifying",
  "悠久": "long-standing; having a long history",
  "所": "classifier for buildings or institutions; place",
  "打招呼": "to greet; to say hello",
  "数码": "digital; numerical code",
  "根本": "fundamental; at all, usually in a negative clause",
  "棒": "excellent; stick",
  "橡皮": "eraser; rubber",
  "欠": "to owe; to lack; to yawn",
  "沙滩": "beach; sandy shore",
  "沟通": "to communicate; to connect",
  "烂": "rotten; broken; overcooked",
  "现象": "phenomenon",
  "电台": "radio station; transceiver",
  "答应": "to agree; to promise; to answer",
  "系": "department; system; relationship",
  "罐头": "canned food; can",
  "聚会": "social gathering; get-together",
  "象棋": "Chinese chess; xiangqi",
  "闻": "to smell; to hear",
  "除非": "unless; only if",
  "项": "item; classifier for items; nape",
  "频道": "TV or radio channel",
  "一丝不苟": "meticulous; scrupulous",
  "一律": "uniformly; without exception",
  "不屑一顾": "to dismiss as beneath one's notice",
  "主流": "mainstream; main current",
  "举足轻重": "to have a decisive influence",
  "争气": "to make someone proud through one's efforts",
  "以至": "to the extent that; even",
  "任重道远": "to have a heavy responsibility and a long way to go",
  "保管": "to keep safe; to take care of",
  "全力以赴": "to devote all one's effort",
  "公告": "public announcement; to announce publicly",
  "公认": "widely recognized; generally accepted",
  "农历": "traditional Chinese lunar calendar",
  "凑合": "to make do; to get by",
  "分歧": "difference of opinion; disagreement",
  "反动": "reactionary; politically regressive",
  "发火": "to lose one's temper; to catch fire",
  "哎哟": "ouch; oh dear",
  "固执": "stubborn; obstinate",
  "常务": "executive; standing, for an organizational role",
  "平原": "plain; flat lowland",
  "庸俗": "vulgar; commonplace",
  "心态": "mindset; mental attitude",
  "心血": "effort and dedication",
  "慢性": "chronic; slow-acting",
  "慷慨": "generous; impassioned",
  "拔苗助长": "to spoil progress by trying to force it",
  "拘留": "to detain someone; detention",
  "效益": "benefit; effectiveness",
  "敷衍": "to do perfunctorily; to fob someone off",
  "斩钉截铁": "resolute; unequivocal",
  "时差": "time difference; jet lag",
  "栋": "classifier for buildings",
  "株": "classifier for plants; plant",
  "沾光": "to benefit through an association with someone",
  "漂浮": "to float; to drift",
  "生机": "vitality; a chance of survival",
  "疲惫": "exhausted; worn out",
  "盲目": "blindly; without thinking",
  "神仙": "immortal; supernatural being",
  "私自": "without permission; on one's own authority",
  "素食": "vegetarian food; vegetarian diet",
  "统筹兼顾": "to plan as a whole while considering all interests",
  "聋哑": "deaf and unable to speak",
  "胸怀": "breadth of mind; aspirations; to cherish",
  "落实": "to implement; to put into effect",
  "表彰": "to commend publicly",
  "要命": "terrible; unbearable; life-threatening",
  "赞叹": "to exclaim in admiration",
  "过渡": "transition; to move from one stage to another",
  "部署": "to deploy; to arrange",
  "附和": "to echo someone's opinion; to agree along with",
  "陈述": "to state; statement",
  "随手": "as one does something; casually; readily",
  "须知": "instructions; things one should know",
  "验收": "to inspect and accept a delivery or completed work",
  "高尚": "noble; admirable",
  "俩": "two; both",
  "干": "to do; to work",
  "丙": "third; label C; third Heavenly Stem",
  "乙": "second; label B; second Heavenly Stem",
  "甲": "first; label A; first Heavenly Stem",
  "背": "back; to memorize",
  "哇": "wow",
  "大意": "careless",
  "拄": "to lean on a walking stick; to support oneself with",
  "挨": "to suffer; to endure",
  "条理": "logical order; organization",
  "淋": "to drench; to sprinkle",
  "澄清": "to clarify; clear",
  "生态": "ecology; ecological conditions",
  "粉碎": "to smash; to crush",
  "起哄": "to make a noisy disturbance; to heckle",
  "领先": "to be ahead; to lead",
  "丁": "fourth; label D; fourth Heavenly Stem",
  "哈": "ha; sound of laughter",
  "蒙": "to cover; to receive; to suffer",
  "得罪": "to offend; to make a faux pas",
};

// Modern display variants verified against the review’s CC-CEDICT snapshot.
// Keep source forms for sense selection; normalize only their displayed spelling.
const reviewedDisplayPinyin = <String, String>{
  "系领带": "jì lǐng dài",
  "纽扣儿": "niǔ kòu r",
  "致力于": "zhì lì yú",
  "欧洲": "Ōu zhōu",
  "嘱咐": "zhǔ fu",
  "吩咐": "fēn fu",
  "大不了": "dà bu liǎo",
  "码头": "mǎ tou",
  "泄露": "xiè lòu",
};

const reviewedDisplayTraditional = <String, String>{
  "小伙子": "小夥子",
  "事迹": "事蹟",
  "合伙": "合夥",
  "生锈": "生鏽",
};

// Repair truncated references without replacing the remaining source senses.
const reviewedMeaningReplacements = <String, Map<String, String>>{
  "甲": {
    "Heavenly Stems 干": "Heavenly Stems 十天干",
    "baojia 甲 system": "baojia 保甲 system",
  },
  "乙": {
    "Heavenly Stems 干": "Heavenly Stems 十天干",
    "usually 方, as opposed to 方": "usually 乙方, as opposed to 甲方",
  },
  "丙": {"Heavenly Stems 干": "Heavenly Stems 十天干"},
  "丁": {"Heavenly Stems 干": "Heavenly Stems 天干"},
  "哈": {"abbr. for 奇, husky": "abbr. for 哈士奇, husky"},
  "高速": {"abbr. for 路": "abbr. for 高速公路"},
  "立方": {"abbr. for 米": "abbr. for 立方米"},
  "泰斗": {"abbr. for 斗": "abbr. for 泰山北斗"},
  "法人": {"see also 人": "see also 自然人"},
  "得罪": {"see also 罪": "see also 得罪 (dé zuì)"},
  "淡季": {"see also 季": "see also 旺季"},
  "嫌": {"abbr. for 犯": "abbr. for 嫌犯"},
  "泄露": {"also pr. [xiè lòu]": "also pr. [xiè lù]"},
};

// The source’s personal-name tags describe other analyses of these headwords.
const wordsWithUnrelatedNameTags = <String>{
  "东西",
  "钱",
  "一起",
  "张",
  "白",
  "关",
  "夏",
  "班",
  "祝",
  "马",
  "黄",
  "叶子",
  "孙子",
  "帅",
  "戴",
  "汤",
  "丁",
  "内科",
  "布",
  "毛",
  "王子",
  "管子",
  "钟",
  "雷",
  "龙",
  "丛",
  "周边",
  "天才",
  "孔",
  "温和",
  "雷达",
  "鞠躬",
  "高峰",
  "高明",
};
